name: Report to packtracker.io
on: [push]
jobs:
  build:
    name: report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run next.js build
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
        run: |
          sudo apt-get update && sudo apt-get install git yarn -y && sudo rm -rf /var/lib/apt/lists/*
          yarn
          yarn build
